# Generated by Django 4.2.7 on 2023-12-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
